---
# send test mail to admin
- name: test mail
  shell: echo "Test mail from new/updated MSTMP at" `hostname -f` | mail root -s "Test SMTP at `hostname -f`"
  tags: mail
  when: msmtp_send_test_mail
