---
# send test mail to admin
- name: test mail
  shell: echo -e "Test mail from new/updated mSTMP\n\n $(uname -a)" | mail -s "Test mSMTP at $(hostname -f)" root
  tags: mail
  when: msmtp_send_test_mail
  async: 30
  poll: 5
