---
## /* vim: set ft=yaml tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: 'Converge'
  hosts: 'all'
  become: true
  gather_facts: true

  pre_tasks:
  - name: 'Update apt cache'
    ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 600
    when: "ansible_facts['os_family'] == 'Debian'"

  tasks:
  - name: 'Include the role'
    ansible.builtin.include_role:
      name: 'mireiawen.msmtp'
